apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: "kubenews"
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_PASSWORD
            value: "pg#123"

---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kube-news
  template:
    metadata:
      labels:
        app: kube-news
    spec:
      containers:
      - name: kube-news
        image: maiconghidolin/kube-news:v2
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "pg#123"
        - name: DB_HOST
          value: "postgre"

---

apiVersion: v1
kind: Service
metadata:
  name: kube-news-nodeport
spec:
  selector:
    app: kube-news
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
